import os
import json
import time
import google.genai as genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()
client = genai.Client(api_key=os.environ["GOOGLE_GENERATIVEAI_API_KEY"])

TARGET_MODEL = 'gemini-3.1-flash-lite-preview'

# ==========================================
# 1. Generating Test Scenarios
# ==========================================
def generate_dataset():
    """Creates 5 specific situations based on your AlertType"""
    prompt = """
   Generate 5 test scenarios for an IoT system.
    Available error types (AlertType):
    1. MALFUNCTION (High percentage of invalid data, broken JSON)
    2. SECURITY_SPAM (Excessive message sending frequency, suspected DDoS)
    3. CRITICAL_DIRECTION (Temperature is moving in the opposite direction from the setpoint)
    4. STUCK (Temperature does not reach the target value within the allotted time)
    5. OFFLINE (No data from the device during the Heartbeat timeout)
    
    Return an array of 5 JSON objects (one for each type). Format:
    {
        "alert_type": "The error type from the list",
        "scenario": "A detailed description of what is physically happening with the device in real life"
    }
    """
    
    response = client.models.generate_content(
        model=TARGET_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.7 
        )
    )
    return json.loads(response.text)


# ==========================================
# 2. Code Graders
# ==========================================
def validate_json(text):
    """Checks if the agent returned valid JSON to prevent the React frontend from crashing"""
    try:
        json.loads(text.strip())
        return 10
    except json.JSONDecodeError:
        return 0
    
   

# ==========================================
# 3. Model Grader
# ==========================================
def grade_by_model(test_case, output):
    """Evaluates how useful the agent's advice is in a real-world situation"""
    eval_prompt = f"""
    You are a Senior IoT Engineer. Evaluate the advice generated by an AI assistant for a duty operator.
    
    Situation:
    Error Type: {test_case['alert_type']}
    Description: {test_case['scenario']}
    
    Assistant's Advice: {output}
    
    Evaluate how safe, logical, and technically sound the advice is.
    (For example, if for CRITICAL_DIRECTION the agent just advises to wait - that is bad. If it advises checking the wiring polarity - that is good).
    
    Return a JSON with the following keys:
    - "strengths": an array of strong points
    - "weaknesses": an array of weak points or risks
    - "score": a number from 1 to 10
    """
    
    response = client.models.generate_content(
        model=TARGET_MODEL,
        contents=eval_prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.1
        )
    )
    return json.loads(response.text)


# ==========================================
# 4. Execution
# ==========================================
def run_prompt(test_case):
    """THIS IS WHERE EVOLUTION HAPPENS! This is the brain of your agent."""
    prompt = f"""
    You are an assistant to a duty IoT engineer. Analyze the device error and provide troubleshooting advice.
    
    ERROR: {test_case['alert_type']}
    DETAILS: {test_case['scenario']}
    
    Return strict JSON with the following keys:
    - "diagnosis": "brief possible cause",
    - "action_plan": "step-by-step troubleshooting advice",
    - "severity": "MEDIUM, HIGH, or CRITICAL"
    """
    response = client.models.generate_content(
        model=TARGET_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.2
        )
    )
    clean_text = response.text.replace("```json", "").replace("```python", "").replace("```", "").strip()
    return clean_text


def run_eval(dataset):
    results = []
    
    for test_case in dataset:
        print(f"Testing scenario: {test_case['alert_type']}...")
        
        # 1. Return result
        output = run_prompt(test_case)
        
        # 2. Grade syntax (Code)
        syntax_score = validate_json(output)
        
        # 3. Grade logic (Model)
        model_grade = grade_by_model(test_case, output)
        
        # 4. Calculate average
        final_score = (syntax_score + model_grade['score']) / 2
        
        results.append({
            "task": test_case["alert_type"],
            "syntax_score": syntax_score,
            "logic_score": model_grade['score'],
            "final_score": final_score
        })

        print("Waiting 10 seconds to respect API rate limits...\n")
        time.sleep(15)
        
    return results

# Execution
if __name__ == "__main__":
    print("Generating dataset...")
    my_dataset = generate_dataset()
    
    print("\nRunning evaluation...")
    evaluation_results = run_eval(my_dataset)
    
    print("\nFINAL REPORT:")
    print(json.dumps(evaluation_results, indent=2, ensure_ascii=False))