import os
import json
import time
import concurrent.futures
import google.genai as genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

TARGET_MODEL = 'gemini-3.1-flash-lite-preview'

class PromptEvaluator:
    def __init__(self, max_concurrent_tasks=3):
        """
        Initializes the evaluator. 
        max_concurrent_tasks=3 safely prevents Free Tier 429 Rate Limit errors.
        """
        self.client = genai.Client(api_key=os.environ["GOOGLE_GENERATIVEAI_API_KEY"])
        self.max_concurrent_tasks = max_concurrent_tasks

    # ==========================================
    # 1. Generating Test Scenarios
    # ==========================================
    def generate_dataset(self, num_scenarios=3):
        """Creates {num_scenarios} specific situations based on your AlertType"""
        prompt = f"""
        Generate {num_scenarios} test scenarios for an IoT system.
        Available error types (AlertType):
        1. MALFUNCTION (High percentage of invalid data, broken JSON)
        2. SECURITY_SPAM (Excessive message sending frequency, suspected DDoS)
        3. CRITICAL_DIRECTION (Temperature is moving in the opposite direction from the setpoint)
        4. STUCK (Temperature does not reach the target value within the allotted time)
        5. OFFLINE (No data from the device during the Heartbeat timeout)
        
        Return an array of {num_scenarios} JSON objects (one for each type). Format:
        {{
            "alert_type": "The error type from the list",
            "scenario": "A detailed description of what is physically happening with the device in real life"
        }}
        """
        
        response = self.client.models.generate_content(
            model=TARGET_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.7 
            )
        )
        return json.loads(response.text)

    # ==========================================
    # 2. Code Graders
    # ==========================================
    def validate_json(self, text):
        """Checks if the agent returned valid JSON to prevent the React frontend from crashing"""
        try:
            json.loads(text.strip())
            return 10
        except json.JSONDecodeError:
            return 0

    # ==========================================
    # 3. Model Grader
    # ==========================================
    def grade_by_model(self, test_case, output, extra_criteria=""):
        """Evaluates how useful the agent's advice is in a real-world situation"""
        eval_prompt = f"""
        You are a Senior IoT Engineer. Evaluate the advice generated by an AI assistant for a duty operator.
        
        Situation:
        Error Type: {test_case['alert_type']}
        Description: {test_case['scenario']}
        
        Assistant's Advice: {output}

        GRADING CRITERIA:
        1. Is it physically safe and logical?
        2. Does it resolve the root cause?
        {extra_criteria}
        
        Return a JSON with the following keys:
        - "strengths": [list of strings]
        - "weaknesses": [list of strings]
        - "score": number from 1 to 10
        """
        
        response = self.client.models.generate_content(
            model=TARGET_MODEL,
            contents=eval_prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.1
            )
        )
        return json.loads(response.text)
    
    def _evaluate_single_case(self, test_case, agent_function, extra_criteria):
        """Internal worker function for the thread pool."""
        try:
            # 1. Get the agent's answer
            agent_output = agent_function(self.client, test_case)
            
            # 2. Check JSON syntax (Code Grader)
            syntax_score = self.validate_json(agent_output)
                
            # 3. Get the Judge's score (Model Grader)
            model_grade = self.grade_by_model(test_case, agent_output, extra_criteria)

            final_score = (syntax_score + model_grade['score']) / 2
            
            return {
                "alert": test_case.get("alert_type", "UNKNOWN"),
                "device": test_case.get("device_type", "UNKNOWN"),
                "syntax_score": syntax_score,
                "logic_score": model_grade.get("score", 0),
                "final_score": final_score,
                "strengths": model_grade.get("strengths", []),
                "weaknesses": model_grade.get("weaknesses", [])
            }
        except Exception as e:
            return {"alert": test_case.get("alert_type", "UNKNOWN"), "error": str(e)}
    
    def run_eval(self, agent_function, dataset, extra_criteria=""):
        """Orchestrates the evaluation using Concurrency Control."""
        print(f"\nRunning evaluation on {len(dataset)} cases with max_concurrency={self.max_concurrent_tasks}...")
        results = []
        
        with concurrent.futures.ThreadPoolExecutor(max_workers=self.max_concurrent_tasks) as executor:
            futures = [
                executor.submit(self._evaluate_single_case, case, agent_function) 
                for case in dataset
            ]

            for future in concurrent.futures.as_completed(futures):
                results.append(future.result())
                print(f"Completed a test case.")
                # Tiny pause to ensure we don't trip the absolute peak RPM limits
                time.sleep(2)
            
        return results

# ==========================================
# 4. Execution
# ==========================================
def run_prompt(client, test_case):
    """
    ITERATION 4: The Ultimate Prompt (XML + Process Steps + Guidelines + Few-Shot Examples).
    """
    prompt = f"""
    You are an expert duty IoT engineer. Analyze the provided telemetry data and provide troubleshooting advice.

    <examples>
      <example>
        <context>
          This example shows how to handle a tricky physical installation error and format the output perfectly.
        </context>
        <sample_telemetry>
          <error_code>CRITICAL_DIRECTION</error_code>
          <physical_symptoms>The system is calling for cooling, but the temperature is rising rapidly.</physical_symptoms>
        </sample_telemetry>
        <ideal_output>
          {{
            "diagnosis": "The cooling valve is likely wired in reverse (polarity flipped) or mechanically installed backward, causing it to heat when it should cool.",
            "action_plan": [
              "Immediately override the valve to manual OFF to prevent further heating.",
              "Dispatch a technician to check the physical wiring polarity of the actuator.",
              "Save alert to device memory."
            ],
            "safety_risk": true
          }}
        </ideal_output>
      </example>
    </examples>
    
    <telemetry_data>
        <error_type>{test_case.get('alert_type', '')}</error_type>
        <physical_symptoms>{test_case.get('scenario', '')}</physical_symptoms>
    </telemetry_data>

    <process_steps>
        Before providing the JSON answer, follow these steps:
        1. Analyze the physical mechanism of the device based on the telemetry data.
        2. Identify the root cause of the error.
        3. Determine if this poses a physical safety risk to the facility.
        4. Formulate a step-by-step repair plan.
    </process_steps>
    
    <output_guidelines>
        - Return STRICT VALID JSON only. No markdown formatting outside the JSON.
        - Key "diagnosis": A short string explaining the root cause.
        - Key "action_plan": An array of strings (max 3 steps).
        - Key "safety_risk": A boolean (true/false).
        - MANDATORY: The final step in the "action_plan" MUST be exactly: "Save alert to device memory."
    </output_guidelines>
    """

    response = client.models.generate_content(
        model=TARGET_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.2
        )
    )
    clean_text = response.text.replace("```json", "").replace("```python", "").replace("```", "").strip()
    return clean_text

# Execution
if __name__ == "__main__":
    # 1. Initialize the Evaluator with safe concurrency limits
    evaluator = PromptEvaluator(max_concurrent_tasks=2)

    print("Generating dataset...")
    test_dataset = evaluator.generate_dataset(num_scenarios=3)

    strict_rules = """
    MANDATORY REQUIREMENTS:
    - The action plan MUST include a step reminding the engineer to save the alert and final command to the device's local memory.
    - If it's a STUCK error, it MUST suggest checking the mechanical actuators.
    Deduct points heavily if these are missing.
    """
    
    print("\nRunning evaluation...")
    evaluation_results = evaluator.run_eval(
        agent_function=run_prompt,
        dataset=test_dataset,
        extra_criteria=strict_rules
    )
    
    print("\nFINAL REPORT:")
    print(json.dumps(evaluation_results, indent=2, ensure_ascii=False))